apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  my-password: cGFzc3dvcmRAMTIz    
  
  
  
# this is encrypted password using " echo -n <your-password> | base64"
# echo -n password@123 | base64 =====>>> cGFzc3dvcmRAMTIz
